// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: C5_Dual_antenna

#include "ui.h"
#include "../../ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenW
lv_obj_t *ui_ScreenW_screen_init(lv_obj_t *parent);
void ui_event_ScreenW(lv_event_t * e);
lv_obj_t * ui_ScreenW;
lv_obj_t * ui_ScreenW_Chart;
lv_obj_t * ui_ScreenW_Chart_Xaxis;
lv_obj_t * ui_ScreenW_Chart_Yaxis1;
lv_obj_t * ui_ScreenW_Chart_Yaxis2;
lv_obj_t * ui_ScreenW_LabelTitle;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenWP
void ui_ScreenWP_screen_init(void);
void ui_event_ScreenWP(lv_event_t * e);
lv_obj_t * ui_ScreenWP;
lv_obj_t * ui_ScreenWP_LabelTitle;
lv_obj_t * ui_ScreenWP_LabelPoint;
lv_obj_t * ui_ScreenWP_LabelPointSelect;
lv_obj_t * ui_Container2;
lv_obj_t * ui_ScreenWP_Chart;
lv_obj_t * ui_ScreenWP_Chart_Xaxis;
lv_obj_t * ui_ScreenWP_Chart_Yaxis1;
lv_obj_t * ui_ScreenWP_Chart_Yaxis2;
lv_obj_t * ui_ScreenWP_Chart1;
lv_obj_t * ui_ScreenWP_Chart1_Xaxis;
lv_obj_t * ui_ScreenWP_Chart1_Yaxis1;
lv_obj_t * ui_ScreenWP_Chart1_Yaxis2;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenM
void ui_ScreenM_screen_init(void);
void ui_event_ScreenM(lv_event_t * e);
lv_obj_t * ui_ScreenM;
lv_obj_t * ui_ScreenM_LabelPoint;
lv_obj_t * ui_ScreenM_LabelPointSelect;
lv_obj_t * ui_ScreenM_Chart;
lv_obj_t * ui_ScreenM_Chart_Xaxis;
lv_obj_t * ui_ScreenM_Chart_Yaxis1;
lv_obj_t * ui_ScreenM_Chart_Yaxis2;
lv_obj_t * ui_ScreenW_LabelTitle2;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenS
void ui_ScreenS_screen_init(void);
void ui_event_ScreenS(lv_event_t * e);
lv_obj_t * ui_ScreenS;
lv_obj_t * ui_ScreenS_LabelPoint;
lv_obj_t * ui_ScreenS_LabelPointSelect;
lv_obj_t * ui_ScreenS_LabelTitle;
lv_obj_t * ui_ScreenS_Container;
lv_obj_t * ui_ScreenS_LabelLIghtTitle;
lv_obj_t * ui_ScreenS_LabelLightNum;
void ui_event_ScreenS_SliderLight(lv_event_t * e);
lv_obj_t * ui_ScreenS_SliderLight;

lv_obj_t *ui_csi_behav_Screen_screen_init(lv_obj_t *parent);
lv_obj_t * uic_csi_behav_lab;
lv_obj_t * uic_csi_day_rigt_lab;
lv_obj_t * uic_csi_day_rigt_but;
lv_obj_t * uic_csi_day_left_lab;
lv_obj_t * uic_csi_day_left_but;
lv_obj_t * uic_csi_day_data_lab;
lv_obj_t * uic_csi_3_but_cont;
lv_obj_t * uic_csi_3_unoccupied_lab;
lv_obj_t * uic_csi_3_unoccupied_pan;
lv_obj_t * uic_csi_3_occupied_lab;
lv_obj_t * uic_csi_3_occupied_pan;
lv_obj_t * uic_csi_3_pie_arc2;
lv_obj_t * uic_csi_3_pie_arc1;
lv_obj_t * uic_csi_3_pie_arc;
lv_obj_t * uic_csi_3_circle_line;
lv_obj_t * uic_csi_3_Dial_img;
lv_obj_t * uic_csi_3_pie_cont;
lv_obj_t * uic_CSi_3_page;
lv_obj_t * uic_csi_behav_tab;
lv_obj_t * uic_csi_cont_behavior;
lv_obj_t * uic_csi_behav_Screen;
lv_obj_t * ui_csi_behav_Screen = NULL;
lv_obj_t * ui_csi_cont_behavior = NULL;
lv_obj_t * ui_csi_behav_tab = NULL;
lv_obj_t * ui_CSi_3_page = NULL;
lv_obj_t * ui_csi_3_pie_cont = NULL;
lv_obj_t * ui_csi_3_Dial_img = NULL;
lv_obj_t * ui_csi_3_circle_line = NULL;
lv_obj_t * ui_csi_3_pie_arc = NULL;
lv_obj_t * ui_csi_3_pie_arc1 = NULL;
lv_obj_t * ui_csi_3_pie_arc2 = NULL;
lv_obj_t * ui_csi_3_occupied_pan = NULL;
lv_obj_t * ui_csi_3_occupied_lab = NULL;
lv_obj_t * ui_csi_3_unoccupied_pan = NULL;
lv_obj_t * ui_csi_3_unoccupied_lab = NULL;
lv_obj_t * ui_csi_3_but_cont = NULL;
lv_obj_t * ui_csi_day_data_lab = NULL;
lv_obj_t * ui_csi_day_left_but = NULL;
lv_obj_t * ui_csi_day_left_lab = NULL;
lv_obj_t * ui_csi_day_rigt_but = NULL;
lv_obj_t * ui_csi_day_rigt_lab = NULL;
lv_obj_t * ui_csi_behav_lab = NULL;
// CUSTOM VARIABLES

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenW(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_ScreenWP, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenWP_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_ScreenS, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenS_screen_init);
    }
}

void ui_event_ScreenWP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_ScreenS, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenS_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        //_ui_screen_change(&ui_ScreenW, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenW_screen_init);
    }
}

void ui_event_ScreenM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_ScreenWP, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenWP_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_ScreenS, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenS_screen_init);
    }
}

void ui_event_ScreenS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_ScreenWP, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenWP_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        //_ui_screen_change(&ui_ScreenW, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenW_screen_init);
    }
}

void ui_event_ScreenS_SliderLight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_ScreenS_LabelLightNum, target, "", "");
        ScreenSSliderLight_function(e);
    }
}