// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: C5_Dual_antenna

#ifndef _C5_DUAL_ANTENNA_UI_H
#define _C5_DUAL_ANTENNA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_events.h"


// SCREEN: ui_ScreenW
lv_obj_t *ui_ScreenW_screen_init(lv_obj_t *parent);
void ui_event_ScreenW(lv_event_t * e);
extern lv_obj_t * ui_ScreenW;
extern lv_obj_t * ui_ScreenW_Chart;
extern lv_obj_t * ui_ScreenW_Chart_Xaxis;
extern lv_obj_t * ui_ScreenW_Chart_Yaxis1;
extern lv_obj_t * ui_ScreenW_Chart_Yaxis2;
extern lv_obj_t * ui_ScreenW_LabelTitle;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenWP
void ui_ScreenWP_screen_init(void);
void ui_event_ScreenWP(lv_event_t * e);
extern lv_obj_t * ui_ScreenWP;
extern lv_obj_t * ui_ScreenWP_LabelTitle;
extern lv_obj_t * ui_ScreenWP_LabelPoint;
extern lv_obj_t * ui_ScreenWP_LabelPointSelect;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_ScreenWP_Chart;
extern lv_obj_t * ui_ScreenWP_Chart_Xaxis;
extern lv_obj_t * ui_ScreenWP_Chart_Yaxis1;
extern lv_obj_t * ui_ScreenWP_Chart_Yaxis2;
extern lv_obj_t * ui_ScreenWP_Chart1;
extern lv_obj_t * ui_ScreenWP_Chart1_Xaxis;
extern lv_obj_t * ui_ScreenWP_Chart1_Yaxis1;
extern lv_obj_t * ui_ScreenWP_Chart1_Yaxis2;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenM
void ui_ScreenM_screen_init(void);
void ui_event_ScreenM(lv_event_t * e);
extern lv_obj_t * ui_ScreenM;
extern lv_obj_t * ui_ScreenM_LabelPoint;
extern lv_obj_t * ui_ScreenM_LabelPointSelect;
extern lv_obj_t * ui_ScreenM_Chart;
extern lv_obj_t * ui_ScreenM_Chart_Xaxis;
extern lv_obj_t * ui_ScreenM_Chart_Yaxis1;
extern lv_obj_t * ui_ScreenM_Chart_Yaxis2;
extern lv_obj_t * ui_ScreenW_LabelTitle2;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenS
void ui_ScreenS_screen_init(void);
void ui_event_ScreenS(lv_event_t * e);
extern lv_obj_t * ui_ScreenS;
extern lv_obj_t * ui_ScreenS_LabelPoint;
extern lv_obj_t * ui_ScreenS_LabelPointSelect;
extern lv_obj_t * ui_ScreenS_LabelTitle;
extern lv_obj_t * ui_ScreenS_Container;
extern lv_obj_t * ui_ScreenS_LabelLIghtTitle;
extern lv_obj_t * ui_ScreenS_LabelLightNum;
void ui_event_ScreenS_SliderLight(lv_event_t * e);
extern lv_obj_t * ui_ScreenS_SliderLight;

lv_obj_t *ui_csi_behav_Screen_screen_init(lv_obj_t *parent);
extern lv_obj_t * uic_csi_behav_lab;
extern lv_obj_t * uic_csi_day_rigt_lab;
extern lv_obj_t * uic_csi_day_rigt_but;
extern lv_obj_t * uic_csi_day_left_lab;
extern lv_obj_t * uic_csi_day_left_but;
extern lv_obj_t * uic_csi_day_data_lab;
extern lv_obj_t * uic_csi_3_but_cont;
extern lv_obj_t * uic_csi_3_unoccupied_lab;
extern lv_obj_t * uic_csi_3_unoccupied_pan;
extern lv_obj_t * uic_csi_3_occupied_lab;
extern lv_obj_t * uic_csi_3_occupied_pan;
extern lv_obj_t * uic_csi_3_pie_arc2;
extern lv_obj_t * uic_csi_3_pie_arc1;
extern lv_obj_t * uic_csi_3_pie_arc;
extern lv_obj_t * uic_csi_3_circle_line;
extern lv_obj_t * uic_csi_3_Dial_img;
extern lv_obj_t * uic_csi_3_pie_cont;
extern lv_obj_t * uic_CSi_3_page;
extern lv_obj_t * uic_csi_behav_tab;
extern lv_obj_t * uic_csi_cont_behavior;
extern lv_obj_t * uic_csi_behav_Screen;
extern lv_obj_t * ui_csi_behav_Screen;
extern lv_obj_t * ui_csi_cont_behavior;
extern lv_obj_t * ui_csi_behav_tab;
extern lv_obj_t * ui_CSi_3_page;
extern lv_obj_t * ui_csi_3_pie_cont;
extern lv_obj_t * ui_csi_3_Dial_img;
extern lv_obj_t * ui_csi_3_circle_line;
extern lv_obj_t * ui_csi_3_pie_arc;
extern lv_obj_t * ui_csi_3_pie_arc1;
extern lv_obj_t * ui_csi_3_pie_arc2;
extern lv_obj_t * ui_csi_3_occupied_pan;
extern lv_obj_t * ui_csi_3_occupied_lab;
extern lv_obj_t * ui_csi_3_unoccupied_pan;
extern lv_obj_t * ui_csi_3_unoccupied_lab;
extern lv_obj_t * ui_csi_3_but_cont;
extern lv_obj_t * ui_csi_day_data_lab;
extern lv_obj_t * ui_csi_day_left_but;
extern lv_obj_t * ui_csi_day_left_lab;
extern lv_obj_t * ui_csi_day_rigt_but;
extern lv_obj_t * ui_csi_day_rigt_lab;
extern lv_obj_t * ui_csi_behav_lab;
// CUSTOM VARIABLES

// EVENTS

// extern lv_obj_t * ui____initial_actions0;
LV_IMG_DECLARE(ui_img_979141937);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
