// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: echoear_csi

#include "../ui.h"
#include "../../../custom_ui.h"
// event funtions

// build funtions

lv_obj_t *ui_csi_behav_Screen_screen_init(lv_obj_t *parent)
{
    ui_csi_behav_Screen = lv_obj_create(parent);
    lv_obj_set_size(ui_csi_behav_Screen, SCREEN_WIDTH, SCREEN_HEIGHT);
    lv_obj_set_style_bg_color(ui_csi_behav_Screen, lv_color_hex(0x000000), 0);
    lv_obj_set_style_border_width(ui_csi_behav_Screen, 0, 0);
    lv_obj_set_style_pad_all(ui_csi_behav_Screen, 0, 0);
    lv_obj_clear_flag(ui_csi_behav_Screen, LV_OBJ_FLAG_SCROLLABLE);

    ui_csi_cont_behavior = lv_obj_create(ui_csi_behav_Screen);
    lv_obj_remove_style_all(ui_csi_cont_behavior);
    lv_obj_set_width(ui_csi_cont_behavior, 360);
    lv_obj_set_height(ui_csi_cont_behavior, 307);
    lv_obj_set_x(ui_csi_cont_behavior, 0);
    lv_obj_set_y(ui_csi_cont_behavior, -26);
    lv_obj_set_align(ui_csi_cont_behavior, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_csi_cont_behavior, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_csi_behav_tab = lv_tabview_create(ui_csi_cont_behavior);
    lv_tabview_set_tab_bar_size(ui_csi_behav_tab, 0);
    lv_obj_set_width(ui_csi_behav_tab, 277);
    lv_obj_set_height(ui_csi_behav_tab, 293);
    lv_obj_set_x(ui_csi_behav_tab, 0);
    lv_obj_set_y(ui_csi_behav_tab, 20);
    lv_obj_set_align(ui_csi_behav_tab, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_csi_behav_tab, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_csi_behav_tab, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_csi_behav_tab, lv_color_hex(0xC0C0C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_csi_behav_tab, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_csi_behav_tab), lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_csi_behav_tab), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CSi_3_page = lv_tabview_add_tab(ui_csi_behav_tab, "Summary");
    lv_obj_remove_flag(ui_CSi_3_page, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CSi_3_page, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CSi_3_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CSi_3_page, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_CSi_3_page, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_CSi_3_page, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_CSi_3_page, 0, LV_PART_SCROLLBAR | LV_STATE_CHECKED);

    ui_csi_3_pie_cont = lv_obj_create(ui_CSi_3_page);
    lv_obj_remove_style_all(ui_csi_3_pie_cont);
    lv_obj_set_width(ui_csi_3_pie_cont, 300);
    lv_obj_set_height(ui_csi_3_pie_cont, 280);
    lv_obj_set_x(ui_csi_3_pie_cont, 2);
    lv_obj_set_y(ui_csi_3_pie_cont, 3);
    lv_obj_set_align(ui_csi_3_pie_cont, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_csi_3_pie_cont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_csi_3_Dial_img = lv_image_create(ui_csi_3_pie_cont);
    lv_image_set_src(ui_csi_3_Dial_img, &ui_img_979141937);
    lv_obj_set_width(ui_csi_3_Dial_img, LV_SIZE_CONTENT);   /// 250
    lv_obj_set_height(ui_csi_3_Dial_img, LV_SIZE_CONTENT);    /// 223
    lv_obj_set_x(ui_csi_3_Dial_img, -2);
    lv_obj_set_y(ui_csi_3_Dial_img, 0);
    lv_obj_set_align(ui_csi_3_Dial_img, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_csi_3_Dial_img, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_csi_3_Dial_img, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_csi_3_Dial_img, 288);

    ui_csi_3_circle_line = lv_arc_create(ui_csi_3_pie_cont);
    lv_obj_set_width(ui_csi_3_circle_line, 191);
    lv_obj_set_height(ui_csi_3_circle_line, 191);
    lv_obj_set_align(ui_csi_3_circle_line, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_csi_3_circle_line, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_csi_3_circle_line, 0, 360);
    lv_arc_set_value(ui_csi_3_circle_line, 234);
    lv_arc_set_bg_angles(ui_csi_3_circle_line, 0, 360);
    lv_obj_set_style_arc_color(ui_csi_3_circle_line, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_csi_3_circle_line, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_csi_3_circle_line, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_csi_3_circle_line, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_csi_3_circle_line, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_csi_3_circle_line, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_csi_3_circle_line, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_csi_3_pie_arc = lv_arc_create(ui_csi_3_pie_cont);
    lv_obj_set_width(ui_csi_3_pie_arc, 191);
    lv_obj_set_height(ui_csi_3_pie_arc, 191);
    lv_obj_set_align(ui_csi_3_pie_arc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_csi_3_pie_arc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_csi_3_pie_arc, 0, 360);
    lv_arc_set_value(ui_csi_3_pie_arc, 120);
    lv_arc_set_bg_angles(ui_csi_3_pie_arc, 0, 360);
    lv_obj_set_style_arc_color(ui_csi_3_pie_arc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_csi_3_pie_arc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_csi_3_pie_arc, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_csi_3_pie_arc, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_csi_3_pie_arc, lv_color_hex(0x6B9FF8), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_csi_3_pie_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_csi_3_pie_arc, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_csi_3_pie_arc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_csi_3_pie_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_csi_3_pie_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_csi_3_pie_arc1 = lv_arc_create(ui_csi_3_pie_cont);
    lv_obj_set_width(ui_csi_3_pie_arc1, 191);
    lv_obj_set_height(ui_csi_3_pie_arc1, 191);
    lv_obj_set_align(ui_csi_3_pie_arc1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_csi_3_pie_arc1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_csi_3_pie_arc1, 0, 360);
    lv_arc_set_value(ui_csi_3_pie_arc1, 3);
    lv_arc_set_bg_angles(ui_csi_3_pie_arc1, 0, 360);
    lv_arc_set_rotation(ui_csi_3_pie_arc1, 250);
    lv_obj_set_style_arc_color(ui_csi_3_pie_arc1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_csi_3_pie_arc1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_csi_3_pie_arc1, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_csi_3_pie_arc1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_csi_3_pie_arc1, lv_color_hex(0x6B9FF8), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_csi_3_pie_arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_csi_3_pie_arc1, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_csi_3_pie_arc1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_csi_3_pie_arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_csi_3_pie_arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_csi_3_pie_arc2 = lv_arc_create(ui_csi_3_pie_cont);
    lv_obj_set_width(ui_csi_3_pie_arc2, 191);
    lv_obj_set_height(ui_csi_3_pie_arc2, 191);
    lv_obj_set_align(ui_csi_3_pie_arc2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_csi_3_pie_arc2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_csi_3_pie_arc2, 0, 360);
    lv_arc_set_value(ui_csi_3_pie_arc2, 40);
    lv_arc_set_bg_angles(ui_csi_3_pie_arc2, 0, 360);
    lv_arc_set_rotation(ui_csi_3_pie_arc2, 170);
    lv_obj_set_style_arc_color(ui_csi_3_pie_arc2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_csi_3_pie_arc2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_csi_3_pie_arc2, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_csi_3_pie_arc2, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_csi_3_pie_arc2, lv_color_hex(0x6B9FF8), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_csi_3_pie_arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_csi_3_pie_arc2, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_csi_3_pie_arc2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_csi_3_pie_arc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_csi_3_pie_arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_csi_3_occupied_pan = lv_obj_create(ui_csi_3_pie_cont);
    lv_obj_set_width(ui_csi_3_occupied_pan, 10);
    lv_obj_set_height(ui_csi_3_occupied_pan, 10);
    lv_obj_set_x(ui_csi_3_occupied_pan, -32);
    lv_obj_set_y(ui_csi_3_occupied_pan, -15);
    lv_obj_set_align(ui_csi_3_occupied_pan, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_csi_3_occupied_pan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_csi_3_occupied_pan, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_csi_3_occupied_pan, lv_color_hex(0x6B9FF8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_csi_3_occupied_pan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_csi_3_occupied_pan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_csi_3_occupied_pan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_csi_3_occupied_pan, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_csi_3_occupied_lab = lv_label_create(ui_csi_3_pie_cont);
    lv_obj_set_width(ui_csi_3_occupied_lab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_csi_3_occupied_lab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_csi_3_occupied_lab, 9);
    lv_obj_set_y(ui_csi_3_occupied_lab, -15);
    lv_obj_set_align(ui_csi_3_occupied_lab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_csi_3_occupied_lab, "Occupied");
    lv_obj_set_style_text_color(ui_csi_3_occupied_lab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_csi_3_occupied_lab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_csi_3_occupied_lab, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_csi_3_unoccupied_pan = lv_obj_create(ui_csi_3_pie_cont);
    lv_obj_set_width(ui_csi_3_unoccupied_pan, 10);
    lv_obj_set_height(ui_csi_3_unoccupied_pan, 10);
    lv_obj_set_x(ui_csi_3_unoccupied_pan, -32);
    lv_obj_set_y(ui_csi_3_unoccupied_pan, 3);
    lv_obj_set_align(ui_csi_3_unoccupied_pan, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_csi_3_unoccupied_pan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_csi_3_unoccupied_pan, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_csi_3_unoccupied_pan, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_csi_3_unoccupied_pan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_csi_3_unoccupied_pan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_csi_3_unoccupied_pan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_csi_3_unoccupied_pan, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_csi_3_unoccupied_lab = lv_label_create(ui_csi_3_pie_cont);
    lv_obj_set_width(ui_csi_3_unoccupied_lab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_csi_3_unoccupied_lab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_csi_3_unoccupied_lab, 16);
    lv_obj_set_y(ui_csi_3_unoccupied_lab, 2);
    lv_obj_set_align(ui_csi_3_unoccupied_lab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_csi_3_unoccupied_lab, "Unoccupied");
    lv_obj_set_style_text_color(ui_csi_3_unoccupied_lab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_csi_3_unoccupied_lab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_csi_3_unoccupied_lab, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_csi_3_but_cont = lv_obj_create(ui_CSi_3_page);
    lv_obj_remove_style_all(ui_csi_3_but_cont);
    lv_obj_set_width(ui_csi_3_but_cont, 256);
    lv_obj_set_height(ui_csi_3_but_cont, 250);
    lv_obj_set_align(ui_csi_3_but_cont, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_csi_3_but_cont, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_csi_3_but_cont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_csi_day_data_lab = lv_label_create(ui_csi_3_but_cont);
    lv_obj_set_width(ui_csi_day_data_lab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_csi_day_data_lab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_csi_day_data_lab, 0);
    lv_obj_set_y(ui_csi_day_data_lab, -110);
    lv_obj_set_align(ui_csi_day_data_lab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_csi_day_data_lab, "2025.08.13");
    lv_obj_set_style_text_color(ui_csi_day_data_lab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_csi_day_data_lab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_csi_day_left_but = lv_button_create(ui_csi_3_but_cont);
    lv_obj_set_width(ui_csi_day_left_but, 61);
    lv_obj_set_height(ui_csi_day_left_but, 28);
    lv_obj_set_x(ui_csi_day_left_but, -67);
    lv_obj_set_y(ui_csi_day_left_but, -106);
    lv_obj_set_align(ui_csi_day_left_but, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_csi_day_left_but, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_csi_day_left_but, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_csi_day_left_but, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_csi_day_left_but, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_csi_day_left_but, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_csi_day_left_but, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_csi_day_left_but, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_csi_day_left_but, lv_color_hex(0xA7A7A7), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_csi_day_left_but, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_csi_day_left_lab = lv_label_create(ui_csi_day_left_but);
    lv_obj_set_width(ui_csi_day_left_lab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_csi_day_left_lab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_csi_day_left_lab, 16);
    lv_obj_set_y(ui_csi_day_left_lab, -4);
    lv_obj_set_align(ui_csi_day_left_lab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_csi_day_left_lab, "<");
    lv_obj_set_style_text_color(ui_csi_day_left_lab, lv_color_hex(0xCFCFCF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_csi_day_left_lab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_csi_day_rigt_but = lv_button_create(ui_csi_3_but_cont);
    lv_obj_set_width(ui_csi_day_rigt_but, 61);
    lv_obj_set_height(ui_csi_day_rigt_but, 28);
    lv_obj_set_x(ui_csi_day_rigt_but, 77);
    lv_obj_set_y(ui_csi_day_rigt_but, -106);
    lv_obj_set_align(ui_csi_day_rigt_but, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_csi_day_rigt_but, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_csi_day_rigt_but, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_csi_day_rigt_but, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_csi_day_rigt_but, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_csi_day_rigt_but, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_csi_day_rigt_but, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_csi_day_rigt_but, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_csi_day_rigt_but, lv_color_hex(0xA7A7A7), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_csi_day_rigt_but, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_csi_day_rigt_lab = lv_label_create(ui_csi_day_rigt_but);
    lv_obj_set_width(ui_csi_day_rigt_lab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_csi_day_rigt_lab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_csi_day_rigt_lab, -27);
    lv_obj_set_y(ui_csi_day_rigt_lab, -3);
    lv_obj_set_align(ui_csi_day_rigt_lab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_csi_day_rigt_lab, ">");
    lv_obj_set_style_text_color(ui_csi_day_rigt_lab, lv_color_hex(0xCFCFCF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_csi_day_rigt_lab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_csi_behav_lab = lv_label_create(ui_csi_behav_Screen);
    lv_obj_set_width(ui_csi_behav_lab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_csi_behav_lab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_csi_behav_lab, 0);
    lv_obj_set_y(ui_csi_behav_lab, -132);
    lv_obj_set_align(ui_csi_behav_lab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_csi_behav_lab, "Behavior Detection");
    lv_obj_set_style_text_color(ui_csi_behav_lab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_csi_behav_lab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_csi_behav_lab, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_csi_behav_Screen = ui_csi_behav_Screen;
    uic_csi_cont_behavior = ui_csi_cont_behavior;
    uic_csi_behav_tab = ui_csi_behav_tab;
    uic_CSi_3_page = ui_CSi_3_page;
    uic_csi_3_pie_cont = ui_csi_3_pie_cont;
    uic_csi_3_Dial_img = ui_csi_3_Dial_img;
    uic_csi_3_circle_line = ui_csi_3_circle_line;
    uic_csi_3_pie_arc = ui_csi_3_pie_arc;
    uic_csi_3_pie_arc1 = ui_csi_3_pie_arc1;
    uic_csi_3_pie_arc2 = ui_csi_3_pie_arc2;
    uic_csi_3_occupied_pan = ui_csi_3_occupied_pan;
    uic_csi_3_occupied_lab = ui_csi_3_occupied_lab;
    uic_csi_3_unoccupied_pan = ui_csi_3_unoccupied_pan;
    uic_csi_3_unoccupied_lab = ui_csi_3_unoccupied_lab;
    uic_csi_3_but_cont = ui_csi_3_but_cont;
    uic_csi_day_data_lab = ui_csi_day_data_lab;
    uic_csi_day_left_but = ui_csi_day_left_but;
    uic_csi_day_left_lab = ui_csi_day_left_lab;
    uic_csi_day_rigt_but = ui_csi_day_rigt_but;
    uic_csi_day_rigt_lab = ui_csi_day_rigt_lab;
    uic_csi_behav_lab = ui_csi_behav_lab;

    // lv_obj_update_layout(ui_csi_behav_Screen);

    /* 默认隐藏，由页面管理器控制显示 */
    lv_obj_add_flag(ui_csi_behav_Screen, LV_OBJ_FLAG_HIDDEN);

    return ui_csi_behav_Screen;
}

void ui_csi_behav_Screen_screen_destroy(void)
{
    if(ui_csi_behav_Screen) lv_obj_del(ui_csi_behav_Screen);

    // NULL screen variables
    uic_csi_behav_Screen = NULL;
    ui_csi_behav_Screen = NULL;
    uic_csi_cont_behavior = NULL;
    ui_csi_cont_behavior = NULL;
    uic_csi_behav_tab = NULL;
    ui_csi_behav_tab = NULL;
    uic_CSi_3_page = NULL;
    ui_CSi_3_page = NULL;
    uic_csi_3_pie_cont = NULL;
    ui_csi_3_pie_cont = NULL;
    uic_csi_3_Dial_img = NULL;
    ui_csi_3_Dial_img = NULL;
    uic_csi_3_circle_line = NULL;
    ui_csi_3_circle_line = NULL;
    uic_csi_3_pie_arc = NULL;
    ui_csi_3_pie_arc = NULL;
    uic_csi_3_pie_arc1 = NULL;
    ui_csi_3_pie_arc1 = NULL;
    uic_csi_3_pie_arc2 = NULL;
    ui_csi_3_pie_arc2 = NULL;
    uic_csi_3_occupied_pan = NULL;
    ui_csi_3_occupied_pan = NULL;
    uic_csi_3_occupied_lab = NULL;
    ui_csi_3_occupied_lab = NULL;
    uic_csi_3_unoccupied_pan = NULL;
    ui_csi_3_unoccupied_pan = NULL;
    uic_csi_3_unoccupied_lab = NULL;
    ui_csi_3_unoccupied_lab = NULL;
    uic_csi_3_but_cont = NULL;
    ui_csi_3_but_cont = NULL;
    uic_csi_day_data_lab = NULL;
    ui_csi_day_data_lab = NULL;
    uic_csi_day_left_but = NULL;
    ui_csi_day_left_but = NULL;
    uic_csi_day_left_lab = NULL;
    ui_csi_day_left_lab = NULL;
    uic_csi_day_rigt_but = NULL;
    ui_csi_day_rigt_but = NULL;
    uic_csi_day_rigt_lab = NULL;
    ui_csi_day_rigt_lab = NULL;
    uic_csi_behav_lab = NULL;
    ui_csi_behav_lab = NULL;

}
