// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: C5_Dual_antenna

#include "../ui.h"
#include "../../../alarm_manager.h"

lv_obj_t *ui_ScreenW_screen_init(lv_obj_t *parent)
{
    /* ================= Root container ================= */
    ui_ScreenW = lv_obj_create(parent);
    lv_obj_set_size(ui_ScreenW, SCREEN_WIDTH, SCREEN_HEIGHT);
    lv_obj_set_style_bg_color(ui_ScreenW, lv_color_hex(0x000000), 0);
    lv_obj_set_style_border_width(ui_ScreenW, 0, 0);
    lv_obj_set_style_pad_all(ui_ScreenW, 0, 0);
    lv_obj_clear_flag(ui_ScreenW, LV_OBJ_FLAG_SCROLLABLE);


    ui_ScreenW_Chart = lv_chart_create(ui_ScreenW);
    lv_obj_set_width(ui_ScreenW_Chart, 280);
    lv_obj_set_height(ui_ScreenW_Chart, 160);
    lv_obj_set_x(ui_ScreenW_Chart, 10);
    lv_obj_set_y(ui_ScreenW_Chart, 6);
    lv_obj_set_align(ui_ScreenW_Chart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreenW_Chart,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_ScreenW_Chart, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_ScreenW_Chart, LV_CHART_TYPE_LINE);
    lv_obj_set_style_bg_color(ui_ScreenW_Chart, lv_color_hex(0xFDFCF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenW_Chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ScreenW_Chart, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScreenW_Chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenW_Chart_Xaxis = lv_scale_create(ui_ScreenW_Chart);
    lv_scale_set_mode(ui_ScreenW_Chart_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_ScreenW_Chart_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_ScreenW_Chart_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_ScreenW_Chart_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_ScreenW_Chart,
                                                                          LV_PART_MAIN) + lv_obj_get_style_border_width(ui_ScreenW_Chart, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_ScreenW_Chart_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ScreenW_Chart_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_ScreenW_Chart_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ScreenW_Chart_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_ScreenW_Chart_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_ScreenW_Chart_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_ScreenW_Chart_Xaxis, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_ScreenW_Chart_Xaxis, 2 >= 1 ? 2 : 1);
    ui_ScreenW_Chart_Yaxis1 = lv_scale_create(ui_ScreenW_Chart);
    lv_scale_set_mode(ui_ScreenW_Chart_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_ScreenW_Chart_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_ScreenW_Chart_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_ScreenW_Chart_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_ScreenW_Chart,
                                                                          LV_PART_MAIN) - lv_obj_get_style_border_width(ui_ScreenW_Chart, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_ScreenW_Chart_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ScreenW_Chart_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_ScreenW_Chart_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ScreenW_Chart_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_ScreenW_Chart_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_ScreenW_Chart_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_ScreenW_Chart_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_ScreenW_Chart_Yaxis2 = lv_scale_create(ui_ScreenW_Chart);
    lv_scale_set_mode(ui_ScreenW_Chart_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_align(ui_ScreenW_Chart_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_line_width(ui_ScreenW_Chart_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ScreenW_Chart_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_ScreenW_Chart_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ScreenW_Chart_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_ScreenW_Chart_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_ScreenW_Chart_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_ScreenW_Chart_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_ScreenW_Chart_Yaxis2, false);

    lv_obj_set_style_size(ui_ScreenW_Chart, 0, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_ScreenW_Chart_Xaxis, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenW_Chart_Xaxis, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ScreenW_Chart_Yaxis1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenW_Chart_Yaxis1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ScreenW_Chart_Yaxis2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenW_Chart_Yaxis2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenW_Chart_Xaxis, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenW_Chart_Yaxis1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenW_Chart_Yaxis2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_ScreenW_Chart, LV_MAX3(50, 50, 0),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_ScreenW_Chart, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_ScreenW_LabelTitle = lv_label_create(ui_ScreenW);
    lv_obj_set_width(ui_ScreenW_LabelTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenW_LabelTitle, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_ScreenW_LabelTitle, 0);
    lv_obj_set_y(ui_ScreenW_LabelTitle, -100);
    lv_obj_set_align(ui_ScreenW_LabelTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenW_LabelTitle, " CSI Waveform Amplitude ");
    lv_obj_set_style_text_color(ui_ScreenW_LabelTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenW_LabelTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenW_LabelTitle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ScreenW_LabelTitle, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenW_LabelPoint = lv_label_create(ui_ScreenW);
    lv_obj_set_width(ui_ScreenW_LabelPoint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenW_LabelPoint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenW_LabelPoint, 0);
    lv_obj_set_y(ui_ScreenW_LabelPoint, 147);
    lv_obj_set_align(ui_ScreenW_LabelPoint, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenW_LabelPoint, "....");
    lv_obj_set_style_text_color(ui_ScreenW_LabelPoint, lv_color_hex(0x393838), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenW_LabelPoint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenW_LabelPoint, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenW_LabelPointSelect = lv_label_create(ui_ScreenW);
    lv_obj_set_width(ui_ScreenW_LabelPointSelect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenW_LabelPointSelect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenW_LabelPointSelect, -17);
    lv_obj_set_y(ui_ScreenW_LabelPointSelect, 147);
    lv_obj_set_align(ui_ScreenW_LabelPointSelect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenW_LabelPointSelect, ".");
    lv_obj_set_style_text_color(ui_ScreenW_LabelPointSelect, lv_color_hex(0x9D9D9D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenW_LabelPointSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenW_LabelPointSelect, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* ================= Layout finalize ================= */
    lv_obj_update_layout(ui_ScreenW);

    /* 默认隐藏，由页面管理器控制显示 */
    lv_obj_add_flag(ui_ScreenW, LV_OBJ_FLAG_HIDDEN);

    return ui_ScreenW;
}
